### ISSUE TITLE
Add short description to cards

### ISSUE THREAD

**Issue by eileenfuerstenau** [eileenfuerstenau/capstone-project#4]

**Comment by eileenfuerstenau** [comment]
**Value proposition (user story)**

As a user
I want to see a short book description and expand it on click
in order to have an idea what a book is about

**Description (text, scribble, design)**
Short description text of the book, expandable on click

<img width="556" alt="2nd user story" src="https://user-images.githubusercontent.com/77294653/110140921-e7c63f00-7dd4-11eb-967e-809f5484a412.png">

**Acceptance criteria (edge cases)**

- [ ] Multiple book-cards with cover, title and author

Complexity (S, M, L)

S

**Tasks**

- [ ] Create feature branch
- [ ] Create book card component (storybook)
- [ ] Fetch data from API
- [ ] Add data to book cards
- [ ] Render booklist in App
- [ ] Add missing styles
